const assert = require('node:assert/strict');
require('./rewards-core.js');
const e = globalThis.RewardEngine;
const event = (id, extra={}) => ({id:String(id),key:'english:normal:survival',mode:'survival',seconds:60,units:10,metric:10,...extra});
let r = e.award(e.fresh(), event(1));
assert.equal(r.xp,30);
assert.equal(r.coins,55);
assert.deepEqual(r.badges,['first','survivor']);
assert.equal(e.award(r.state,event(1)).xp,0);
assert.equal(e.award(r.state,event(2,{seconds:2})).xp,0);
assert.equal(e.award(r.state,event(2,{units:0})).xp,0);
for(let i=2;i<=10;i++) r=e.award(r.state,event(i));
assert.equal(r.xp,45);
assert.equal(r.coins,35);
assert.equal(r.state.rounds,10);
assert.equal(r.state.xp,235);
const original = r.state;
const purchased = e.purchase(original,'frame-gold');
assert.equal(purchased.coins,original.coins-80);
assert.equal(original.owned.length,0);
assert.equal(e.purchase(purchased,'frame-gold').coins,purchased.coins);
assert.equal(e.equip(purchased,'frame-gold').equipped.frame,'frame-gold');
assert.throws(()=>e.purchase(e.fresh(),'frame-gold'));
assert.throws(()=>e.equip(e.fresh(),'frame-gold'));
r=e.award(r.state,event(11,{mode:'ghostrace',key:'ghost:phrase1',metric:20,lowerIsBetter:true,ghostWon:true}));
assert(r.badges.includes('ghost'));
r=e.award(r.state,event(12,{mode:'ghostrace',key:'ghost:phrase1',metric:25,lowerIsBetter:true}));
assert.equal(r.personalBest,false);
r=e.award(r.state,event(13,{mode:'ghostrace',key:'ghost:phrase2',metric:25,lowerIsBetter:true}));
assert.equal(r.personalBest,true);
r=e.award(r.state,event(14,{mode:'defense',units:50,combo:50}));
assert(r.badges.includes('defender') && r.badges.includes('combo'));
for(let i=15;i<=25;i++) r=e.award(r.state,event(i));
assert(r.badges.includes('veteran'));
assert.deepEqual(e.normalize(JSON.parse(JSON.stringify(r.state))),r.state);
assert.deepEqual(e.normalize({coins:-1,xp:NaN,owned:['fake'],equipped:{frame:'frame-gold'}}),e.fresh());
assert.equal(e.fresh().xp,0);
console.log('Reward tests passed: awards, duplicate prevention, milestones, badges, purchases, equipment, backup normalization and fresh Guest state.');
