(function(){
    'use strict';
    const packs=[
        {id:'pharmaceutical',purchase:'wordpack-pharmaceutical',name:'Pharmaceutical Medicines',words:['acetaminophen','amoxicillin','amlodipine','atorvastatin','azithromycin','cephalexin','cetirizine','ciprofloxacin','clindamycin','dexamethasone','diclofenac','doxycycline','enalapril','fluconazole','furosemide','gabapentin','hydrochlorothiazide','ibuprofen','insulin','levothyroxine','losartan','metformin','metoprolol','montelukast','naproxen','omeprazole','ondansetron','pantoprazole','paracetamol','prednisone','salbutamol','simvastatin','spironolactone','tramadol','valsartan']},
        {id:'medical',purchase:'wordpack-medical',name:'Medical Terminologies',words:['abdomen','anatomy','antibody','artery','auscultation','biopsy','cardiology','diagnosis','edema','epidermis','fracture','hematology','hypertension','immunity','inflammation','intravenous','metabolism','neurology','oncology','pathology','prognosis','radiology','respiration','systolic','tachycardia','therapy','thoracic','thrombosis','toxicology','ultrasound','vascular','ventricle','vertebra','virology','wound']},
        {id:'chemistry',purchase:'wordpack-chemistry',name:'Chemistry',words:['acid','alkaline','anion','atom','beaker','catalyst','cation','chlorine','compound','covalent','crystal','diffusion','electron','electrolyte','element','equilibrium','evaporation','flask','hydrogen','isotope','laboratory','molecule','neutron','nitrogen','oxidation','periodic','polymer','precipitate','proton','reaction','reagent','solution','solvent','titration','valence']}
    ];
    function read(){try{const raw=JSON.parse(localStorage.getItem('kw_word_packs'));if(raw&&Array.isArray(raw.enabled))return{classic:raw.classic!==false,enabled:raw.enabled.filter(id=>packs.some(p=>p.id===id))};}catch(error){}return{classic:true,enabled:[]};}
    function save(value){if(currentAppProfile!=='guest')localStorage.setItem('kw_word_packs',JSON.stringify(value));}
    function owned(pack){return !!(window.WarriorRewards&&WarriorRewards.owns(pack.purchase));}
    function words(classic){const state=read(),result=state.classic?classic.slice():[];packs.forEach(pack=>{if(owned(pack)&&state.enabled.includes(pack.id))result.push(...pack.words);});return result.length?Array.from(new Set(result)):classic.slice();}
    function key(){const state=read();return (state.classic?'classic':'special')+'|'+state.enabled.filter(id=>{const pack=packs.find(p=>p.id===id);return pack&&owned(pack);}).sort().join('|');}
    const panel=document.createElement('div');panel.className='setting word-pack-setting';
    panel.innerHTML='<div class="setting-title">Arcade Word Packages</div><div class="setting-description">Choose the word pools used by Keyboard Defense and Typing Survival. Multiple packages can be mixed.</div><div id="wordPackOptions" class="word-pack-options"></div><p id="wordPackStatus" class="setting-description" aria-live="polite"></p><button type="button" class="backup-btn" id="wordPackShop">OPEN WORD PACKAGE SHOP</button>';
    const anchor=document.querySelector('#settingsScreen .version-setting');anchor.before(panel);
    function render(){const state=read(),list=document.getElementById('wordPackOptions');list.replaceChildren();const choices=[{id:'classic',name:'Classic',description:'Words based on the selected Friendly or Almighty attitude.',owned:true},...packs.map(p=>({id:p.id,name:p.name,description:p.words.length+' specialized words.',owned:owned(p)}))];choices.forEach(choice=>{const label=document.createElement('label');label.className='word-pack-option'+(choice.owned?'':' locked');const input=document.createElement('input');input.type='checkbox';input.checked=choice.id==='classic'?state.classic:state.enabled.includes(choice.id);input.disabled=!choice.owned;input.onchange=()=>toggle(choice.id,input.checked);const text=document.createElement('span');text.innerHTML='<strong>'+choice.name+'</strong><small>'+(choice.owned?choice.description:'Locked · Purchase in the Warrior Shop')+'</small>';label.append(input,text);list.append(label);});}
    function toggle(id,checked){const state=read();if(id==='classic')state.classic=checked;else if(checked&&!state.enabled.includes(id))state.enabled.push(id);else state.enabled=state.enabled.filter(x=>x!==id);state.enabled=state.enabled.filter(x=>{const p=packs.find(pack=>pack.id===x);return p&&owned(p);});if(!state.classic&&!state.enabled.length){state.classic=true;document.getElementById('wordPackStatus').textContent='At least one word package must remain enabled.';}else document.getElementById('wordPackStatus').textContent='Arcade word packages updated.';save(state);render();}
    document.getElementById('wordPackShop').onclick=()=>{WarriorRewards.openShop();const select=document.getElementById('shopCategory');select.value='wordpack';select.dispatchEvent(new Event('change'));};
    window.KWWordPacks={words,key,render};render();
})();
